name: Build and deploy workflow
on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t aleksanderdulepov/flask_app_repo:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push aleksanderdulepov/flask_app_repo:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render action.yml
        uses: |
          mkdir deploy
          cat docker-compose-ci.yaml | ensubstv > deploy/docker-compose.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_VM }}
          username: ${{ secrets.USERNAME_VM }}
          password: ${{ secrets.PASSWORD_VM }}
          source: "deploy/docker-compose.yaml"
          target: "light_insta_action"
          strip_components: 1

